### ISSUE TITLE
Overbuffing Weapon Damage

### ISSUE THREAD

**Issue by cfstoecker** [Pantocyclus/InstantSCCS#24]
Would it be possible to save some resources on the weapon damage when it is overcapped to use for the spell damage test?  

Total Weapon Damage: 3798.0
Weapon Damage Test takes 1 adventure (predicted: -13).
Total Spell Damage: 1768.0
Spell Damage Test takes 26 adventures (predicted: 26).

The Cargo Pants pocket (Rictus of Yeg) and the Wizard Snack Voucher (wasabi marble soda) seem like they could have been better be used on the spell damage equivalents in my last ascension.  Detailed data below if it's helpful.

<html>
  <body>
    Equipment changed.<br>

    
type | source | Weapon Damage | Weapon Damage Percent
-- | -- | -- | --
Item | seal-skull helmet | +1.00 | = +1.00 |   |  
Item | dented scepter |   |   | +50.00 | = +50.00
Equipment Power | 15% weapon power | +30.00 | = +31.00 |   |  
Item | august scepter |   |   | +50.00 | = +100.00
Item | pantogram pants | +20.00 | = +51.00 |   |  
Item | Brutal brogues |   |   | +50.00 | = +150.00
Item | Powerful Glove |   |   | +25.00 | = +175.00
Item | Kremlin's Greatest Briefcase |   |   | +25.00 | = +200.00
Equipment Power | 15% weapon power | +15.00 | = +66.00 |   |  
Item | candy cane sword cane | +5.00 | = +71.00 | +50.00 | = +250.00
Skill | Claws of the Walrus | +7.00 | = +78.00 |   |  
Effect | Disdain of the War Snapper | +5.00 | = +83.00 |   |  
Effect | Meteor Showered |   |   | +200.00 | = +450.00
Effect | Billiards Belligerence |   |   | +50.00 | = +500.00
Effect | Jackasses' Symphony of Destruction | +12.00 | = +95.00 |   |  
Effect | Tenacity of the Snapper | +8.00 | = +103.00 |   |  
Effect | Carol of the Bulls |   |   | +100.00 | = +600.00
Effect | Frenzied, Bloody |   |   | +50.00 | = +650.00
Effect | Rage of the Reindeer | +10.00 | = +113.00 |   |  
Effect | Scowl of the Auk | +10.00 | = +123.00 |   |  
Effect | Song of the North |   |   | +100.00 | = +750.00
Effect | Pronounced Potency | +5.00 | = +128.00 |   |  
Effect | Wasabi With You |   |   | +150.00 | = +900.00
Effect | Do You Crush What I Crush? |   |   | +100.00 | = +1000.00
Effect | Destructive Resolve | +20.00 | = +148.00 |   |  
Effect | Seeing Red | +25.00 | = +173.00 | +100.00 | = +1100.00
Effect | Cowrruption |   |   | +200.00 | = +1300.00
Effect | Imported Strength |   |   | +50.00 | = +1350.00
Effect | Weapon of Mass Destruction |   |   | +30.00 | = +1380.00
Effect | The Power of LOV |   |   | +50.00 | = +1430.00
Effect | Lack of Body-Building |   |   | +25.00 | = +1455.00
Effect | Rictus of Yeg |   |   | +200.00 | = +1655.00
Boom Box | These Fists Were Made for Punchin' | +21.00 | = +194.00 |   |  
Effect | Offhand Remarkable |   |   | +50.00 | = +1705.00

  </body>
</html>

[Weapon Damage] seal-skull helmet (1.0)
[Weapon Damage Percent] dented scepter (50.0)
[Weapon Damage] 15% weapon power (30.0)
[Weapon Damage Percent] august scepter (50.0)
[Weapon Damage] pantogram pants (20.0)
[Weapon Damage Percent] Brutal brogues (50.0)
[Weapon Damage Percent] Powerful Glove (25.0)
[Weapon Damage Percent] Kremlin's Greatest Briefcase (25.0)
[Weapon Damage] 15% weapon power (15.0)
[Weapon Damage] candy cane sword cane (5.0)
[Weapon Damage Percent] candy cane sword cane (50.0)
[Weapon Damage] Claws of the Walrus (7.0)
[Weapon Damage] Disdain of the War Snapper (5.0)
[Weapon Damage Percent] Meteor Showered (200.0)
[Weapon Damage Percent] Billiards Belligerence (50.0)
[Weapon Damage] Jackasses' Symphony of Destruction (12.0)
[Weapon Damage] Tenacity of the Snapper (8.0)
[Weapon Damage Percent] Carol of the Bulls (100.0)
[Weapon Damage Percent] Frenzied, Bloody (50.0)
[Weapon Damage] Rage of the Reindeer (10.0)
[Weapon Damage] Scowl of the Auk (10.0)
[Weapon Damage Percent] Song of the North (100.0)
[Weapon Damage] Pronounced Potency (5.0)
[Weapon Damage Percent] Wasabi With You (150.0)
[Weapon Damage Percent] Do You Crush What I Crush? (100.0)
[Weapon Damage] Destructive Resolve (20.0)
[Weapon Damage] Seeing Red (25.0)
[Weapon Damage Percent] Seeing Red (100.0)
[Weapon Damage Percent] Cowrruption (200.0)
[Weapon Damage Percent] Imported Strength (50.0)
[Weapon Damage Percent] Weapon of Mass Destruction (30.0)
[Weapon Damage Percent] The Power of LOV (50.0)
[Weapon Damage Percent] Lack of Body-Building (25.0)
[Weapon Damage Percent] Rictus of Yeg (200.0)
[Weapon Damage] These Fists Were Made for Punchin' (21.0)
[Weapon Damage Percent] Offhand Remarkable (50.0)
[Weapon Damage] Bow-Legged Swagger (194.0)
Weapon Damage => 388.0
[Weapon Damage Percent] Bow-Legged Swagger (1705.0)
Weapon Damage Percent => 3410.0
Total Weapon Damage: 3798.0
Weapon Damage Test takes 1 adventure (predicted: -13).

<html>
  <body>
    <br>

    
type | source | Spell Damage | Spell Damage Percent | Cold Spell Damage | Hot Spell Damage | Sleaze Spell Damage | Spooky Spell Damage | Stench Spell Damage | Sauce Spell Damage
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Item | Hollandaise helmet | +1.00 | = +1.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Item | august scepter |   |   | +50.00 | = +50.00 |   |   |   |   |   |   |   |   |   |   |   |  
Item | Powerful Glove |   |   | +50.00 | = +100.00 |   |   |   |   |   |   |   |   |   |   |   |  
Item | codpiece | +50.00 | = +51.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Item | hewn moon-rune spoon | +10.00 | = +61.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Item | wrench |   |   | +100.00 | = +200.00 |   |   |   |   |   |   |   |   |   |   |   |  
Skill | Eldritch Intellect |   |   |   |   |   |   |   |   |   |   | +1.00 | = +1.00 |   |   |   |  
Skill | Eternal Flame |   |   |   |   |   |   | +1.00 | = +1.00 |   |   |   |   |   |   |   |  
Skill | Master Saucier |   |   | +10.00 | = +210.00 |   |   |   |   |   |   |   |   |   |   |   |  
Skill | Subtle and Quick to Anger |   |   | +10.00 | = +220.00 |   |   |   |   |   |   |   |   |   |   |   |  
Skill | Intrinsic Spiciness |   |   |   |   |   |   |   |   |   |   |   |   |   |   | +10.00 | = +10.00
Effect | Meteor Showered |   |   | +200.00 | = +420.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Jackasses' Symphony of Destruction | +12.00 | = +73.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Arched Eyebrow of the Archmage | +10.00 | = +83.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Carol of the Hells |   |   | +100.00 | = +520.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Mental A-cue-ity |   |   | +50.00 | = +570.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Simmering |   |   | +100.00 | = +670.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Song of Sauce |   |   | +100.00 | = +770.00 |   |   | +50.00 | = +51.00 |   |   |   |   |   |   |   |  
Effect | Visions of the Deep Dark Deeps |   |   | +50.00 | = +820.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Do You Crush What I Crush? |   |   | +100.00 | = +920.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Hot in Herre |   |   |   |   |   |   | +20.00 | = +71.00 |   |   |   |   |   |   |   |  
Effect | Fortunate Resolve | +10.00 | = +93.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Destructive Resolve | +20.00 | = +113.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Lantern-Charged |   |   | +50.00 | = +970.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Cowrruption |   |   | +200.00 | = +1170.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Imported Strength |   |   | +50.00 | = +1220.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | AAA-Charged |   |   | +50.00 | = +1270.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | We're All Made of Starfish |   |   | +25.00 | = +1295.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | The Magic of LOV |   |   | +100.00 | = +1395.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Warlock, Warstock, and Warbarrel |   |   | +150.00 | = +1545.00 |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Hot-Headed |   |   |   |   |   |   | +15.00 | = +86.00 |   |   |   |   |   |   |   |  
Effect | In the 'zone zone! | +50.00 | = +163.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Spirit of Peppermint | +10.00 | = +173.00 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Effect | Offhand Remarkable |   |   | +50.00 | = +1595.00 |   |   |   |   |   |   |   |   |   |   |   |  
  </body>
</html>

[Spell Damage] Hollandaise helmet (1.0)
[Spell Damage Percent] august scepter (50.0)
[Spell Damage Percent] Powerful Glove (50.0)
[Spell Damage] codpiece (50.0)
[Spell Damage] hewn moon-rune spoon (10.0)
[Spell Damage Percent] wrench (100.0)
[Spell Damage Percent] Master Saucier (10.0)
[Spell Damage Percent] Subtle and Quick to Anger (10.0)
[Spell Damage Percent] Meteor Showered (200.0)
[Spell Damage] Jackasses' Symphony of Destruction (12.0)
[Spell Damage] Arched Eyebrow of the Archmage (10.0)
[Spell Damage Percent] Carol of the Hells (100.0)
[Spell Damage Percent] Mental A-cue-ity (50.0)
[Spell Damage Percent] Simmering (100.0)
[Spell Damage Percent] Song of Sauce (100.0)
[Spell Damage Percent] Visions of the Deep Dark Deeps (50.0)
[Spell Damage Percent] Do You Crush What I Crush? (100.0)
[Spell Damage] Fortunate Resolve (10.0)
[Spell Damage] Destructive Resolve (20.0)
[Spell Damage Percent] Lantern-Charged (50.0)
[Spell Damage Percent] Cowrruption (200.0)
[Spell Damage Percent] Imported Strength (50.0)
[Spell Damage Percent] AAA-Charged (50.0)
[Spell Damage Percent] We're All Made of Starfish (25.0)
[Spell Damage Percent] The Magic of LOV (100.0)
[Spell Damage Percent] Warlock, Warstock, and Warbarrel (150.0)
[Spell Damage] In the 'zone zone! (50.0)
[Spell Damage] Spirit of Peppermint (10.0)
[Spell Damage Percent] Offhand Remarkable (50.0)
Spell Damage => 173.0
Spell Damage Percent => 1595.0
Total Spell Damage: 1768.0
Spell Damage Test takes 26 adventures (predicted: 26).

**Comment by Pantocyclus** [comment]
It's not trivial for the script to decide what resources to cut when different accounts with different set-ups may have different goals post-CS.

What you can do is to follow the [FAQ](https://github.com/Pantocyclus/InstantSCCS/?tab=readme-ov-file#im-pretty-shiny---can-i-get-the-script-to-save-certain-resources) and `set instant_explicitlyExcludedBuffs=<comma-separated effect IDs>` to avoid buffing up on various buffs you think you'd like saving.

For example, `set instant_explicitlyExcludedBuffs=2590,827` will prevent the script from using the cargo shorts for Rictus of Yeg and your wizard snack voucher on Wasabi With You (as a small little bonus, the script will then default to using the wizard snack voucher on the spell% potion instead, but will currently not use your cargo shorts for a spell% buff)

**Comment by cfstoecker** [comment]
Thank you for the script!  Just wanted to say that I added the line you recommended, and it no longer uses the Yeg Motel Toothbrush.  It does, however, harvest them from the shorts (I forgot to harvest the Yeg's Motel hand soap before pressing go).

**Comment by Pantocyclus** [comment]
Ah right, that's because there's a separate task specifically for the cargo shorts. You can prevent the toothbrush from being harvested with `set instant_saveCargoShorts=true`.

**Comment by cfstoecker** [comment]
Any chance the script could use the Yeg Motel Soap if it's on hand?

**Comment by Pantocyclus** [comment]
There usually are better pulls for profit (like any of the desk bells), but if you're gunning for something else, this is a little unconventional but it should work - `set instant_spellTestPulls=10607`. If you already have a Motel Soap on hand, it'll skip past pulling from Hagnk's and go directly to using the item.

**Comment by cfstoecker** [comment]
Thank you!  85 turns!
