### ISSUE TITLE
Beaten up from June Cleaver

### ISSUE THREAD

**Issue by syrinzx** [Pantocyclus/InstantSCCS#26]
Looks like InstantSCCS thinks the beaten up from the June Cleaver NC means the last fight was lost.  Also should probably remove the beaten up when fighting scaling monsters:

Executing Leveling/DMT
Preference nextAdventure changed from None to The Deep Machine Tunnels
Putting Tolliam the Melodramedary back into terrarium...
Taking Watchell the Machine Elf out of terrarium...
Maximizer: 0.25 mus, 0.33 ML, -equip tinsel tights, -equip wad of used tape, -"equip Daylight Shavings Helmet", -acc1, -back, -off-hand, -weapon
Maximizing...
4 combinations checked, best score 540.97
Stealing miniature crystal ball from Tolliam the Melodramedary...
Unequipping Tolliam the Melodramedary...
Familiar unequipped.
Putting on miniature crystal ball...
Equipment changed.
Saving outfit: Script Outfit 5
Outfit saved
CCS set to grimoire_macro
Autoattack is disabled.

Visit to Deep Machine Tunnels: The Deep Machine Tunnels in progress...
Preference lastAdventure changed from An Unusually Quiet Barroom Brawl to The Deep Machine Tunnels

[62] The Deep Machine Tunnels
Preference lastEncounter changed from Witchess Bishop to Poetic Justice
Encounter: Poetic Justice
Preference juneCleaverQueue changed from 1468,1475 to 1468,1475,1467
Preference _juneCleaverEncounters changed from 2 to 3
Preference _juneCleaverFightsLeft changed from 0 to 12
You acquire an effect: Beaten Up (5)
You gain 5 Adventures

Preference _concoctionDatabaseRefreshes changed from 413 to 414
lastEncounter =>
Preference lastEncounter changed from Poetic Justice to

Visit to Deep Machine Tunnels: The Deep Machine Tunnels in progress...

[62] The Deep Machine Tunnels
Preference lastEncounter changed from to Realizer of Knowledge and Concepts
Encounter: Realizer of Knowledge and Concepts
Round 0: syrinxlui wins initiative!
Round 1: Your toy train moves ahead to the Viewing Platform. As your train passes the viewing platform, the crowd shouts and cheers inspiring you!
Preference trainsetPosition changed from 45 to 46
Round 1: You gain 364 Beefiness
Round 1: You gain 228 Enchantedness
Round 1: You gain 176 Roguishness
Round 1: syrinxlui executes a macro!
Round 1: syrinxlui casts CURSE OF WEAKSAUCE!
Round 2: You lose 1 or more hit points
Round 2: syrinxlui casts MICROMETEORITE!
Round 3: You lose 1 or more hit points
Preference _micrometeoriteUses changed from 28 to 29
Round 3: syrinxlui casts SING ALONG!
Round 4: You lose 1 or more hit points
Round 4: syrinxlui casts STUFFED MORTAR SHELL!
Round 5: You lose 1 or more hit points
Round 5: syrinxlui casts CINCHO: CONFETTI EXTRAVAGANZA!
Round 6: You lose 1 or more hit points
Preference _cinchUsed changed from 45 to 46
Round 6: syrinxlui casts LUNGING THRUST-SMACK!
Round 7: You lose 1 or more hit points
Round 7: syrinxlui casts LUNGING THRUST-SMACK!
Round 8: syrinxlui wins the fight!
After Battle: Watchell clucks his tongue and time starts passing again. This makes you realize that no time had passed while you were fighting that weird monster.
After Battle: Some extra meat has appeared in your pouch when you weren't looking. Presumably Shadow Savannah's doing.
You gain 12 Meat
After Battle: Did you know that on average every fourth Thinker of Thoughts is actually made of gummy material? You take a bite out of this one, and sure enough, it is!
Preference bookOfFactsGummi changed from 0 to 1
Gummiheart (1)
After Battle: You gain 34 Strengthliness
You gain a Muscle point!
You gain a Mysticality point!
You gain a Moxie point!
Preference _juneCleaverFightsLeft changed from 12 to 11
Preference _juneCleaverHot changed from 4 to 5
Preference encountersUntilDMTChoice changed from 5 to 4
Preference lastCopyableMonster changed from Witchess Bishop to Thinker of Thoughts
This combat did not cost a turn
Preference _machineTunnelsAdv changed from 0 to 1
Preference familiarSweat changed from 48 to 49

Preference _concoctionDatabaseRefreshes changed from 414 to 415
Preference battleAction changed from custom combat script to attack with weapon
hpAutoRecoveryTarget => 0.95
Preference hpAutoRecoveryTarget changed from 0.0 to 0.95
mpAutoRecoveryTarget => 0.05
Preference mpAutoRecoveryTarget changed from 0.0 to 0.05
CCS set to grimoire_macro
(but battle action is currently set to attack with weapon)
choiceAdventure1310 => 0
Preference choiceAdventure1310 changed from 3 to 0
Autoattack is disabled.
JavaScript exception: Fight was lost; stop.

**Comment by Pantocyclus** [comment]
This appears to be an issue with grimoire's automatic handling of June Cleaver's NCs, so there wasn't a way to handle the beaten up prior to running the next fight. 2fe791a62f8083f5c9c2aed66c21fddce588c6ab should resolve this now.
