### ISSUE TITLE
Choice Adventure Handling for Glob of Melted Wax

### ISSUE THREAD

**Issue by syrinzx** [Pantocyclus/InstantSCCS#27]
Seems to be some weirdness in how the Glob of Melted Wax is handled.

Visit to Clan Basement: The Slime Tube in progress...
Preference lastAdventure changed from The Dire Warren to The Slime Tube

[70] The Slime Tube
Preference lastEncounter changed from Adjust your Parka to Showdown
Encounter: Showdown
Preference lastEncounter changed from Showdown to Mother Slime
Encounter: Mother Slime
Round 0: syrinxlui wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 8 to 7
Round 1: Watchell smiles and cheers, and your own voice, now his, speaks inside your head: "You can do this!"
You acquire an effect: Inner Elf (1)
Preference cosmicBowlingBallReturnCombats changed from 7 to 8
Round 1: Your toy train moves ahead to the Meat Mine Sluice. The sluice opens and pours out some meat!
Preference trainsetPosition changed from 73 to 74
You gain 900 Meat.
Round 1: syrinxlui executes a macro!
Round 1: syrinxlui casts KGB TRANQUILIZER DART!
You lose 900 Meat.
Mother Slime banished by KGB tranquilizer dart.
Preference banishedMonsters changed from fluffy bunny:ice house:0:party girl:snokebomb:60:fluffy bunny:Feel Hatred:67 to fluffy bunny:ice house:0:party girl:snokebomb:60:fluffy bunny:Feel Hatred:67:Mother Slime:KGB tranquilizer dart:69
Preference _kgbTranquilizerDartUses changed from 0 to 1
This combat did not cost a turn
Preference familiarSweat changed from 73 to 74

Preference _concoctionDatabaseRefreshes changed from 669 to 670
You are currently a member of Bonus Adventures from Hell
Preference _concoctionDatabaseRefreshes changed from 670 to 671
Preference _instant_kgbTranquilizerDartUses changed from to Weapon Damage/Inner Elf
Weapon Damage/Inner Elf completed!

Executing Weapon Damage/Glob of Melted Wax
CCS set to grimoire_macro
Autoattack is disabled.
Verifying ingredients for wax hand (1)...
Creating 1 wax hand...
You acquire an item: wax hand
Preference _concoctionDatabaseRefreshes changed from 671 to 672
Successfully created wax hand (1)
Whoops! You're not actually in a choice adventure
Preference battleAction changed from custom combat script to attack with weapon
hpAutoRecoveryTarget => 0.95
Preference hpAutoRecoveryTarget changed from 0.0 to 0.95
mpAutoRecoveryTarget => 0.05
Preference mpAutoRecoveryTarget changed from 0.0 to 0.05
CCS set to grimoire_macro
(but battle action is currently set to attack with weapon)
Preference choiceAdventure1387 changed from 3 to -1
choiceAdventure326 => 0
Preference choiceAdventure326 changed from 1 to 0
Autoattack is disabled.
JavaScript exception: KoLmafia error: Whoops! You're not actually in a choice adventure

**Comment by Pantocyclus** [comment]
This was a longstanding bug with using Mafia's `create()` function that I never bothered getting around to resolving. 7f535fb21f053626a6164ede1fb604cbd4dbd620 handles this.
