### ISSUE TITLE
Unable to get codpiece, please help

### ISSUE THREAD

**Issue by shavbi** [Pantocyclus/InstantSCCS#49]
Error message as follows. Only happened a few days ago. Manually getting the codpiece via relay browser moves the script forward. Help please.

Executing Run Start/Get Floundry item
CCS set to grimoire_macro
Autoattack is disabled.
You need 1 more codpiece to continue.
Created an empty checkpoint.
You need 1 more codpiece to continue.
Created an empty checkpoint.
Verifying ingredients for oil cap (1)...
You need 8 more bubblin' crude to continue.
autoSatisfyWithStash => true
Preference autoSatisfyWithStash changed from false to true
Preference customCombatScript changed from grimoire_macro to hccs_aftercore
CCS set to hccs_aftercore
autoSatisfyWithCloset => true
Preference autoSatisfyWithCloset changed from false to true
Autoattack is disabled.
JavaScript exception: Task Run Start/Get Floundry item did not complete within 1 attempts. Please check what went wrong. (file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/instantsccs/instantsccs.js#15023)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/instantsccs/instantsccs.js:15023 (checkLimits)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/instantsccs/instantsccs.js:14740 (execute)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/instantsccs/instantsccs.js:15420 (execute)
at file:/C:/Users/shavb/Dropbox/Games/KoL/Mafia/scripts/instantsccs/instantsccs.js:22342 (main_main)

**Comment by Pantocyclus** [comment]
Seems like KoL changed certain HTML responses which Mafia used to parse for such preference updates. This has ostensibly been fixed (as claimed by a few others), but otherwise we'll have to wait till Mafia updates to handle these changes.

In the meantime, just make sure that you keep your Mafia updated.

**Comment by shavbi** [comment]
noted, thank you for the reply!
